package com.helpmarket.models;
// Generated 07/06/2015 09:42:53 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * DetallePedido generated by hbm2java
 */
public class DetallePedido  implements java.io.Serializable {


     private Integer id;
     private Pedido pedido;
     private BigDecimal cantidad;
     private String producto;
     private BigDecimal precioUnit;
     private BigDecimal total;

    public DetallePedido() {
    }

    public DetallePedido(Pedido pedido, BigDecimal cantidad, String producto, BigDecimal precioUnit, BigDecimal total) {
       this.pedido = pedido;
       this.cantidad = cantidad;
       this.producto = producto;
       this.precioUnit = precioUnit;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }
    public BigDecimal getPrecioUnit() {
        return this.precioUnit;
    }
    
    public void setPrecioUnit(BigDecimal precioUnit) {
        this.precioUnit = precioUnit;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }




}


