package com.helpmarket.models;
// Generated 07/06/2015 09:42:53 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer id;
     private int numero;
     private Date fecha;
     private BigDecimal total;
     private Set detallePedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(int numero, Date fecha) {
        this.numero = numero;
        this.fecha = fecha;
    }
    public Pedido(int numero, Date fecha, BigDecimal total, Set detallePedidos) {
       this.numero = numero;
       this.fecha = fecha;
       this.total = total;
       this.detallePedidos = detallePedidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Set getDetallePedidos() {
        return this.detallePedidos;
    }
    
    public void setDetallePedidos(Set detallePedidos) {
        this.detallePedidos = detallePedidos;
    }




}


